### ISSUE TITLE
Escape key is only triggered on first key press

### ISSUE THREAD

**Issue by samus9001** [samus9001/Quiz-Maker-Exercise#1]
The program only terminates when the escape key is the first key that is pressed. If the user presses another key first then the program will no longer terminate when pressing the escape key. The first key pressed is also ignored when pressed if it is not the escape key, so it appears that the program is specifically listening for the escape key press for the input before the user can continue, which is due to the Console.ReadKey function.

**Comment by samus9001** [comment]
Tried using while (cki.Key != ConsoleKey.Escape) as shown in the ReadKey doc page but any key press is not registered including the escape key when doing so: https://learn.microsoft.com/en-us/dotnet/api/system.console.readkey?view=net-7.0

**Comment by incredibleLeitman** [comment]
The main problem here is that you try to combine the ReadKey and ReadLine methods for reading userinput:
ReadKey only reads the first key the user enters on the console whereas ReadLine wait for any text until Enter is pressed.

So if the user starts by entering another key, your program reads this first key and (if it was no Escape) directly enters the input method for the question.

I suggest you first accept the input for "mode selection" like "Escape" to quit, any other key for entering the question and answers.

Or what is the desired behavior you would like to achieve?

**Comment by samus9001** [comment]
> 

I was thinking of allowing the user to press the Esc key at any point to stop but hadn't thought of the mode approach so I'll give that a go now.

**Comment by incredibleLeitman** [comment]
I really appreciate your effort of making such an intuitive user interface,
but don't put that much time into that ;)

Handling user input and output can be a task to sink hours into,
but does not really help to improve your coding skills and learn new things.

You can try to make this work with a mode, but if you get stuck or things are getting complicated,
just take the easy way out and focus on the actual structure and behavior of your project

**Comment by incredibleLeitman** [comment]
You could either take the approach to ask upfront how many questions/answers the user wants to enter and then just iterate that often

or you can implement the variant of using ReadLine and just check for one specific input like "Do you want to add another question? Y/N" -> if ReadLine != "Y" exit else read another question
