### ISSUE TITLE
Add while loop condition

### ISSUE THREAD

**Issue by henrikmdev** [samus9001/Quiz-Maker-Exercise#11]
https://github.com/samus9001/Quiz-Maker-Exercise/blob/8d707b9956ab9938756c40fd63dc7f5352d873d6/Program.cs#L27
https://github.com/samus9001/Quiz-Maker-Exercise/blob/8d707b9956ab9938756c40fd63dc7f5352d873d6/Program.cs#L39

I personally don't like while(true) loops because if you get into the habit of doing this it runs the risk of having your future code and programs to go into an infinite loop. I prefer while loops that have a condition where it can exit naturally and logically.

For line 27, you can use a condition like "userInput != 'N'". That way you don't even need the if check at the bottom and you may not even need to have that comment at the top. This would make your code simpler.

**Comment by samus9001** [comment]
updated while (!validInput) loop

**Comment by incredibleLeitman** [comment]
this looks better :D
